services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"  # expõe diretamente; cuidado para restringir acesso interno se necessário
    environment:
      - N8N_HOST=n8n.mirako.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.mirako.org/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # Autenticação básica:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=bz1pe5pc
      # Banco Postgres etc, se aplicável...
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:
