services:
  openvpn_mirako:
    image: kylemanna/openvpn:${VERSION}
    # container_name: ${CONTAINER_NAME}   # opcional
    deploy:                               # é ignorado no compose clássico; só tem efeito em Swarm
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - "${HOST_IP}:${OPENVPN_UDP_PORT}:1194/udp"
    restart: always
    volumes:
      - "${APP_PATH}/openvpn:/etc/openvpn"
    labels:
      createdBy: "bt_apps"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.disable_ipv6: "1"
    environment:
      - TZ=${TZ}

